/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Autorisation: typeof import('./src/components/Auth/Autorisation.vue')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LogIn: typeof import('./src/components/Auth/LogIn.vue')['default']
    MainFooter: typeof import('./src/components/MainFooter.vue')['default']
    MainHeader: typeof import('./src/components/MainHeader.vue')['default']
    Register: typeof import('./src/components/Auth/Register.vue')['default']
    Registration: typeof import('./src/components/Auth/Registration.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserMenu: typeof import('./src/components/Header/UserMenu.vue')['default']
  }
}
